version: '3.5'

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 3001:3001  # Expose frontend publicly
    env_file: .env.production  # Production environment variables
    depends_on:
      - server

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 3002:3002  # Expose backend publicly
    env_file: .env.production
    depends_on:
      - db

  db:
    image: mongo:4.2.6
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081  # Expose Mongo Express publicly
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=db
