version: '3.5'

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
    ports:
      - ${CLIENT_PUBLIC_PORT}:${CLIENT_CONTAINER_PORT}
    env_file: .env
    links:
      - server:server
    depends_on:
      - server

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./server:/app:z
      - /app/node_modules
    ports:
      - ${SERVER_PUBLIC_PORT}:${SERVER_CONTAINER_PORT}
    env_file: .env

  db:
    image: mongo:4.2.6
    restart: always
    volumes:
      - ./db/data:/data/db:z
      - ./db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:z
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - ${MONGO_EXPRESS_PUBLIC_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
